### ISSUE TITLE
Bluegene Q xlc smp won't link binaries when compiled with -g: "reference to `__tls_get_addr'" from CpvAccess

### ISSUE THREAD

**Issue by PhilMiller** [UIUC-PPL/charm#104]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/104*

---
With the latest compiler version building `pami-bluegeneq-smp-xlc` with `-g`
```
[phil`vestalac1 commbench]$ which bgxlc_r
/soft/compilers/ibmcmp-feb2013/vac/bg/12.1/bin/bgxlc_r
```
I can't actually link a binary
```
../../../bin/charmc -g -o pgm memoryAccess.o commbench.o overhead.o timer.o proc.o smputil.o pingpong.o broadcast.o reduction.o ctxt.o -language converse++
../../../bin/../lib/libldb-rand.o: In function `CldNodeEnqueue':
/gpfs/vesta-home/phil/charm-6.5/pami-bluegeneq-smp-xlc/tmp/cldb.rand.c:117: undefined reference to `__tls_get_addr'
/gpfs/vesta-home/phil/charm-6.5/pami-bluegeneq-smp-xlc/tmp/cldb.rand.c:122: undefined reference to `__tls_get_addr'
/gpfs/vesta-home/phil/charm-6.5/pami-bluegeneq-smp-xlc/tmp/cldb.rand.c:133: undefined reference to `__tls_get_addr'
../../../bin/../lib/libldb-rand.o: In function `CldEnqueue':
/gpfs/vesta-home/phil/charm-6.5/pami-bluegeneq-smp-xlc/tmp/cldb.rand.c:89: undefined reference to `__tls_get_addr'
/gpfs/vesta-home/phil/charm-6.5/pami-bluegeneq-smp-xlc/tmp/cldb.rand.c:91: undefined reference to `__tls_get_addr'
../../../bin/../lib/libldb-rand.o:/gpfs/vesta-home/phil/charm-6.5/pami-bluegeneq-smp-xlc/tmp/cldb.rand.c:96: more undefined references to `__tls_get_addr' follow
Fatal Error by charmc in directory /home/phil/charm-6.5/pami-bluegeneq-smp-xlc/tests/converse/commbench
   Command bgxlC_r -qhalt=e -I/bgsys/drivers/ppcfloor/comm/sys/include -I/bgsys/drivers/ppcfloor/spi/include -I/bgsys/drivers/ppcfloor -I/bgsys/drivers/ppcfloor/spi/include/kernel/cnk -qnokeyword=__int128 -g -o pgm -L../../../bin/../lib -I../../../bin/../include ../../../bin/../lib/libldb-rand.o memoryAccess.o commbench.o overhead.o timer.o proc.o smputil.o pingpong.o broadcast.o reduction.o ctxt.o moduleinit17300.o ../../../bin/../lib/libmemory-default.o ../../../bin/../lib/libthreads-default.o -lconv-cplus-y -lconv-core -lconv-util -ltrace-converse -lckqt -ldl -L/bgsys/drivers/ppcfloor/comm/sys-fast/lib -lpami -L/bgsys/drivers/ppcfloor/spi/lib -lSPI -lSPI_cnk -lpthread -lrt -lm returned error code 1
charmc exiting...
make: *** [pgm] Error 1

```

[out](https://github.com/UIUC-PPL/charm/files/3536188/out.log)

**Comment by PhilMiller** [comment]
*Original date: 2013-03-14 22:54:25*

---
I've now tried using the previous workaround option `-qsmp:noostls` and got a message that the option was not supported! Same thing on either the November or February compilers, and same thing with `-qsmp:ostls`

**Comment by PhilMiller** [comment]
*Original date: 2013-03-15 03:54:23*

---
Jeff Hammond is treating this as some variant of an old acknowledged compiler bug. I've passed him the tarball to send to the developers, but hopefully we'll get some sort of workaround sooner if they can't fix it quickly.

**Comment by PhilMiller** [comment]
*Original date: 2013-03-29 22:20:56*

---
Passed along to Jeff Hammond, who opened a PMR with IBM about this.

**Comment by heyram** [comment]
*Original date: 2013-04-19 18:26:58*

---
Any updates on this? Or any info of a workaround?
Does this mean we cannot compile smp builds with -g on bgq? That effectively blockades other bughunts.

**Comment by heyram** [comment]
*Original date: 2013-04-25 19:19:54*

---
FWIW, I get the undefined tls errors only if I build charm and the program with -g -O0.
If I build charm with --with-production -g, then I am able to build and run an smp binary successfully.
(ie) charmc (and bgxlC in turn) is quite happy with -optimize -production -g.

My hunch is that bgxlC somehow doesn't like -g -O0 with tls, but is somehow less finicky if some optimization is turned on. This conjecture needs some corroboration.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-01 21:46:05*

---
Forwarded by Jeff Hammond:

On Wed, May 1, 2013 at 3:33 PM, Viktor Ganich <vganich`ca.ibm.com> wrote:
>
> I got the legal clearance to work with Charm++ source code. I downloaded the source from Dropbox that you pointe me to and built it, but I don't really know how to reproduce the problem from this moment on. Could you please pass on the following information:
>
> 1. Options that you've build Charm++ with (I was using: `./build charm++ mpi-linux-ppc  mpicxx     -j16  -g -O0`)
> 2 (optional). The testcase that demonstrates the problem, unless (1) explicitly exposes the problem.
>
> XL C/C++ and Fortran Compilers Service & Support
> IBM Toronto Laboratory | Rational Software
> +1 905-413-4168 (phone)

I responded as follows:

> Following our bug tracker [1], the reproduction is as follows:
> 1. Log in to a system with bgxlc available (I have no clue whether
> this happens with non-Blue Gene XL compilers). For instance, on ALCF's
> Vesta, I see this with
> `/soft/compilers/ibmcmp-feb2013/vacpp/bg/12.1/bin/bgxlC_r` and its
> siblings
> 2. Build Charm++ with the command
> `./build charm++ pami-bluegeneq-smp-xlc -g -O0 -j16`
> 3. Build and try to link a Charm++ binary with the command
> `make -C pami-bluegeneq-smp-xlc/examples/charm++/hello/1darray`
> 
> We've noted that the problem does not occur when compiling the system
> with "`-g -O3`"
> 
> [1] https://charm.cs.illinois.edu/redmine/issues/104

**Comment by PhilMiller** [comment]
*Original date: 2013-05-06 04:29:22*

---
Viktor says
> I was able to reproduce the problem and opened internal document to investigate the problem further. I will provide you with the next status update before or by May 10, 2013.

**Comment by PhilMiller** [comment]
*Original date: 2013-05-30 19:15:52*

---
Reassign for further investigation of prospective `-qsmp:noostls` workaround as actually workable, and incorporation into `cc-xlc.sh` if so.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-04 05:47:17*

---
We need to at least know if the workaround is tenable for the stable release.

(Priority upped for visibility, not to create pressure)

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-07 06:18:51*

---
Very late in realizing that the correct flag is -qsmp=noostls, not -qsmp:noostls. Anyway, this issue is resolved.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-07 06:25:02*

---
It looks like you added the flag to the compiler variable. I thought it produces nasty warnings there and only does something when passed to the linker. If I have that right, why not just add it to the linker variable?

Alternately, does the correct flag as you noted `-qsmp=noostls` rather than `-qsmp:noostls` apply to the compiler and the linker?

**Comment by nikhil-jain** [comment]
*Original date: 2013-06-07 06:29:35*

---
The correct flag is -qsmp=noostls, and it does not produce any nasty warning. ":" should be used to pass multiple variables -qsmp=A:B:C. It can be passed to both compiler/linker - man page of bgxlc does not specify a restriction about passing it to linker.

**Comment by PhilMiller** [comment]
*Original date: 2013-06-07 21:02:02*

---
Grabbed for charm-6.5 stable branch, and tested working on both stable and mainline. Also updated MPI build correspondingly.

**Comment by PhilMiller** [comment]
*Original date: 2013-11-18 22:04:06*

---
This is still happening for ChaNGa when built with -O3, but not with -O2. I've confirmed that the whole build does seem to have `-qsmp=noostls` as it should.

Lukasz noted this back in August, and reported a build log from Charm that shows when this came up. Harshitha just encountered it again as part of pre-release application testing in #343.

```
./build ChaNGa pamilrts-bluegeneq smp xlc --suffix="ChaNGa-smp-globalupd" --with-production -j6 -verbose -DCMK_GLOBAL_LOCATION_UPDATE
```

**Comment by PhilMiller** [comment]
*Original date: 2013-11-18 23:13:19*

---
Just sent another ping to Jeff Hammond and Victor Ganich (IBM) letting them know this is still hitting us.

**Comment by PhilMiller** [comment]
*Original date: 2014-01-29 14:35:45*

---
Viktor reports that IBM's compiler team has reproduced the problem and is investigating the root cause to produce a fix.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-04 22:39:25*

---
Viktor Ganich of IBM writes
> Sorry for late update. It doesn't appear to be a compiler defect after all.
> 
> __tls_get_addr is provided by glibc, in ld.so.1. But BGQ driver defaults to static link (see explanation below), so the driver would pass -static to ld, which is the reason why ld could not find __tls_get_addr in ld.so.1.
> 
> Please use -qnostaticlink on BG/Q for this part of the code. Thank you.
> 
> 
> For your information:
> 
> On Linux, the compiler defaults to -qnostaticlink:
> 
> http://pic.dhe.ibm.com/infocenter/lnxpcomp/v121v141/topic/com.ibm.xlcpp121.linux.doc/compiler_ref/opt_staticlink.html
> 
> on BG/Q, the compiler defaults to -qstaticlink:
> 
> http://pic.dhe.ibm.com/infocenter/compbg/v121v141/topic/com.ibm.xlcpp121.bg.doc/compiler_ref/opt_staticlink.html

**Comment by PhilMiller** [comment]
*Original date: 2014-03-24 19:32:28*

---
Just noticed IBM's release note on XLC about the first round of this: http://www-01.ibm.com/support/docview.wss?uid=swg1LI77397

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-03-25 00:54:37*

---
Following Phil's suggestion, I built charm without the option -qsmp=noostls:noauto on Blue Gene/Q and tried compiling ChaNGa. I still get the same undefined reference to `__tls_get_addr' error.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-28 19:45:03*

---
We've been acting like resolving this is critical for 6.6.0 (despite the targeting to 6.6.1, whose reasoning I failed to record). I would argue that it's not, for a few reasons
* Until we got the suggestion of dynamic linking from IBM, we were fine with sitting on it, rather than pushing on our own to diagnose and fix it.
* It happens only on one platform, using one compiler, only when particular flags are used, and only for certain applications.
* Users of BG/Q in particular can be expected to exhibit a degree of sophistication and awareness in mitigating (i.e. working around) such an issue.

I think for the present 6.6.0 release, we should document the issue, and let the resolution (through the "change from static to dynamic linking":http://charm.cs.uiuc.edu/gerrit/#/c/130 or something else) be driven at its natural pace by the affected application developers.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-28 20:23:39*

---
Using softenv key ibm-compilers-2014-02, I built charm v6.6.0-rc2-48-g80ffb24 as follows:

```
./build ChaNGa pamilrts-bluegeneq smp xlc --suffix="ChaNGa-smp-globalupd" --with-production -j20 -verbose -DCMK_GLOBAL_LOCATION_UPDATE -O3 -qtls=local-exec
```

Note the addition of the explicit TLS model specification, which the "compiler documentation":http://pic.dhe.ibm.com/infocenter/compbg/v121v141/index.jsp?topic=%2Fcom.ibm.xlcpp121.bg.doc%2Flanguage_ref%2Fthread.html&resultof%3D%2522%2574%256c%2573%2522%2520%2522%2574%256c%2522%2520 says should be fastest. It should also remove the need for dynamic linking, if my understanding of the different TLS implementation models is correct.

I then configured ChaNGa with `OPTS=-O3 -qtls=local-exec` in `Makefile.in` using that charm build. When I ran make, it compiled and linked successfully. The resulting binary can be found at 

`~phil/cosmo/changa/ChaNGa`

**Comment by PhilMiller** [comment]
*Original date: 2014-03-28 22:16:13*

---
Charm's own test suite compiled with those options passes, with the exception of `examples/charm++/hello/fancyarray`, which hangs. I suspect that's due to `GLOBAL_LOCATION_UPDATE`, rather than the TLS mode, since there's no unique threading use in that program.

I had to manually compile examples with `OPTS` set on the make command line, since its Makefile doesn't carry the same magic as the tests Makefile does.

**Comment by PhilMiller** [comment]
*Original date: 2014-03-28 22:51:32*

---
That ChaNGa binary passes its own `make test`. Someone from the cosmology subgroup should test its performance and report.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-03-28 22:52:39*

---
I verified that Phil's ChaNGa executable works. Performance is a little hard to judge, due to Phil's use of the global update flag, which makes load balancing more expensive, but leads to no misses in the location cache. With this in mind, here are the results using a dynamically-linked executable, compared to Phil's executable: 

w/ dynamic linking:

v6.6.0-rc2-48-g80ffb24
Charm++> Running on 256 unique compute nodes (64-way SMP).
```
v6.6.0-rc2-48-g80ffb24
Charm++> Running on 256 unique compute nodes (64-way SMP).
Big step   Grav/SPH     DD     LB     TB  Other  Total
       1       4.96   1.43   1.58   0.71   0.59   9.29
       2       5.34   1.37   1.51   0.73   0.58   9.55
       3       5.54   1.39   1.48   0.71   0.58   9.72
       4       5.27   1.42   1.46   0.90   0.60   9.68
       5       5.32   1.43   1.48   0.66   0.59   9.49
       6       5.67   1.37   1.47   0.81   0.57   9.91
       7       6.16   1.40   1.48   0.79   0.56   10.4
       8       6.11   1.47   1.48   0.97   0.59   10.6
       9       6.42   1.41   1.51   0.91   0.57   10.8
     Ave       5.64   1.41   1.50   0.80   0.58   9.95
```
Phil's executable:

v6.6.0-rc2-48-g80ffb24
Charm++> Running on 256 unique compute nodes (64-way SMP).
```
v6.6.0-rc2-48-g80ffb24
Charm++> Running on 256 unique compute nodes (64-way SMP).
Big step   Grav/SPH     DD     LB     TB  Other  Total
       1       5.25   1.41   3.29   0.53   0.55   11.0
       2       5.38   1.36   3.52   0.66   0.58   11.5
       3       4.99   1.41   3.60   0.62   0.58   11.2
       4       5.29   1.39   3.63   0.63   0.59   11.5
       5       5.09   1.50   3.59   0.62   0.57   11.3
       6       5.25   1.41   3.55   0.52   0.57   11.3
       7       4.97   1.38   3.53   0.58   0.59   11.0
       8       5.44   1.52   3.54   0.64   0.60   11.7
       9       5.04   1.45   3.61   0.63   0.60   11.3
     Ave       5.19   1.42   3.54   0.60   0.58   11.3

```

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-03-28 23:18:38*

---
I ran using a new statically-linked binary supplied by Phil, this time without the global location update flag enabled. Results indicate performance is about the same as with the dynamically-linked executable:

```
v6.6.0-rc2-48-g80ffb24
Charm++> Running on 256 unique compute nodes (64-way SMP).
Big step   Grav/SPH     DD     LB     TB  Other  Total
       1       5.50   1.37   1.72   0.80   0.54   9.95
       2       5.52   1.40   1.60   0.82   0.55   9.92
       3       5.76   1.40   1.53   0.85   0.55   10.1
       4       5.48   1.41   1.56   0.95   0.56   9.98
       5       5.39   1.31   1.46   1.04   0.55   9.77
       6       5.83   1.41   1.52   0.93   0.55   10.2
       7       5.85   1.45   1.49   0.86   0.56   10.2
       8       5.69   1.41   1.47   0.67   0.55   9.80
       9       5.78   1.42   1.50   0.86   0.55   10.1
     Ave       5.65   1.40   1.54   0.86   0.55   10.0

```

**Comment by PhilMiller** [comment]
*Original date: 2014-03-29 00:38:34*

---
There's a missing bit of relatively easy-to-get contextual information that might be helpful here in determining impact: what is the performance difference between ChaNGa compiled statically or dynamically with `-O2` and the `-O3` results above?

**Comment by PhilMiller** [comment]
*Original date: 2014-03-29 03:35:13*

---
So, the fancyarray example hangs even when I compile the application with `-qtls=local-exec` without optimization on a build that omits GLOBAL_LOCATION_UPDATE.

Even when I rebuild the runtime system and application without optimization using the current default xlc compilers from November 2013, fancyarray still hangs. Finally, when I rebuild using gcc with options `-O3 -ftls-model=local-exec` it runs successfully.

Incidentally, when I try to build this example, or others around it without `-qtls=local-exec`, I get the undefined reference error. So I can't really pin down whether the problem is the code itself, xlc, an interaction with the TLS model, or what.

**Comment by pplimport** [comment]
*Original author: Lukasz Wesolowski*
*Original date: 2014-03-29 03:49:41*

---
Here are the results for the same ChaNGa run when using -O2 instead of -O3. Performance is about 4% worse.

```

v6.6.0-rc2-48-g80ffb24
Charm++> Running on 256 unique compute nodes (64-way SMP).
Big step   Grav/SPH     DD     LB     TB  Other  Total
       1       6.18   1.40   1.52   0.69   0.57   10.3
       2       6.25   1.37   1.41   0.71   0.58   10.3
       3       6.23   1.35   1.42   0.70   0.58   10.3
       4       6.50   1.46   1.42   0.79   0.61   10.8
       5       6.13   1.44   1.44   0.74   0.58   10.3
       6       6.24   1.45   1.43   0.75   0.58   10.4
       7       5.83   1.48   1.44   0.71   0.61   10.1
       8       6.37   1.47   1.43   0.69   0.59   10.5
       9       6.30   1.46   1.47   0.75   0.57   10.5
     Ave       6.22   1.43   1.44   0.73   0.59   10.4



```

**Comment by PhilMiller** [comment]
*Original date: 2014-03-29 03:51:46*

---
Even dynamically linked to avoid the undefined reference, fancyarray compiled with xlc still hangs. So, it should be independent of anything we do here. Moving further discussion of that to #454.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-01 00:14:24*

---
For people interested in learning more about how this stuff works, Oracle (via Sun) puts out some nice documentation of what's going on under the covers:
http://docs.oracle.com/cd/E26502_01/html/E26507/gentextid-23191.html#scrolltoc
http://docs.oracle.com/cd/E26502_01/html/E26507/chapter8-20.html#gentextid-24227
Obviously, there will be variations in this case for PowerPC, but the general arrangement should be about the same.

**Comment by PhilMiller** [comment]
*Original date: 2014-04-04 22:24:55*

---
Ronak reports that the performance shift in NAMD is under 1%. I think we're done here.
